#' Match history as an R object
#'
#' Visits the url generated by \code{\link{match_history_url}}
#' and parses the JSON into an R object
#'
#' @inheritParams match_history_url
#' @export
#'
raw_match_history <- function (api_key, ...){
  jsonlite::fromJSON(match_history_url(api_key, ...))
}


#' Match Details as an R object
#'
#' Visits the url generated by \code{\link{match_details_url}}
#' and parses the JSON into an R object
#'
#' @inheritParams match_details_url
#' @export
#' @return An R object from the api.
#'
raw_match_details <- function (api_key, match_id, ...){

  jsonlite::fromJSON(match_details_url(api_key, match_id, ...))
}


#' Get a all of a players matches
#'
#' Get a list of game ids that are availible for a player.
#' The maximum number of games that steam remembers for a player is 500
#'
#' @inheritParams match_history_url
#' @param account_id The id of the account whose match id's we want.
#' @param delay The amount of time (in seconds) to wait between api calls.
#' @param verbose Print progress messages?
#' #'
#' @return
#'  A data frame of a players matches, with
#'  a column of match ids. (Integer)
#'  a column of start times, (Integer UNIX time)
#'  a column of of lobby types
#'
#' @export
#'
#' @examples
#'  all_matches(api_key = "<your key>", account_id = 122191358)
all_matches <- function (api_key, account_id, delay = 0.5, verbose = TRUE, ...){
  if (verbose) print("making first api call")

  first <- raw_match_history(api_key, account_id = account_id)

  remaining_calls <- ceiling(first$result$results_remaining / 100)

  output <- data.frame(match_id = first$result$matches$match_id,
                       start_time = first$result$matches$start_time,
                       lobby_type = first$result$matches$lobby_type)


  while(remaining_calls > 0) {
    Sys.sleep(delay)
    if (verbose) print(paste("with", remaining_calls, "remaining"))
    first <- raw_match_history(api_key,
                               account_id = account_id,
                               start_at_match_id = min(output$match_id) - 1)

    output <-   rbind(output, data.frame(match_id = first$result$matches$match_id,
                                     start_time = first$result$matches$start_time,
                                     lobby_type = first$result$matches$lobby_type))
    remaining_calls <- remaining_calls - 1
  }

  return(output)
}


